---
title: "Supported File Types"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# testing collapse


<details>
<summary>Some R code</summary>
  
```{r}
1 + 2
```
</details>



above is from pkgdown.

below is done by me.



<div>
  <h2>Simple Collapsible</h2>
  <p>Click on the button to toggle between showing and hiding content.</p>
  <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo2">Simple Click</button>
  <div id="demo2" class="collapse">
    This is Test
  </div>
</div>



# jsplumb


jsplumb place here


```{r setup}
library(tidycells)
```

# @Dev

This is a Test for DT and collapsibleTree

```{r, echo=FALSE}
DT::datatable(head(iris), style = "bootstrap")
```

Here is a collapsibleTree

```{r, echo=FALSE}
# Create a simple org chart
org <- data.frame(
  Manager = c(
    NA, "Ana", "Ana", "Bill", "Bill", "Bill", "Claudette", "Claudette", "Danny",
    "Fred", "Fred", "Grace", "Larry", "Larry", "Nicholas", "Nicholas"
  ),
  Employee = c(
    "Ana", "Bill", "Larry", "Claudette", "Danny", "Erika", "Fred", "Grace",
    "Henri", "Ida", "Joaquin", "Kate", "Mindy", "Nicholas", "Odette", "Peter"
  ),
  Title = c(
    "President", "VP Operations", "VP Finance", "Director", "Director", "Scientist",
    "Manager", "Manager", "Jr Scientist", "Operator", "Operator", "Associate",
     "Analyst", "Director", "Accountant", "Accountant"
  )
)
collapsibleTree::collapsibleTreeNetwork(org, attribute = "Title")
```

