// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lcs_cc
String lcs_cc(const std::vector< std::string > ss);
RcppExport SEXP _rcpptest_lcs_cc(SEXP ssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector< std::string > >::type ss(ssSEXP);
    rcpp_result_gen = Rcpp::wrap(lcs_cc(ss));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcpptest_lcs_cc", (DL_FUNC) &_rcpptest_lcs_cc, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcpptest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
