# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Longest Common Substring using dynamic programming
#'
#' @param ss a string vector.
#' @keywords internal
#' @examples 
#' LCS(c("hi","hello and hi","only hi"))
LCS <- function(ss) {
    .Call('_tidycells_LCS', PACKAGE = 'tidycells', ss)
}

