# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Longest Common Substring using dynamic programming
#'
#' @param ss a string vector.
#' @keywords internal
#' @examples 
#' LCS(c("hi","hello and hi","only hi"))
LCS <- function(ss) {
    .Call(`_tidycells_LCS`, ss)
}

#' is_attachable for multiple rows of gid1 gid2 composition
#'
#' @param g1g2df a df having 'gid1' 'gid2' columns
#' @keywords internal
is_attachable_multiple <- function(g1g2df, d_dat, d_att, data_attr_map, whole_data) {
    .Call(`_tidycells_is_attachable_multiple`, g1g2df, d_dat, d_att, data_attr_map, whole_data)
}

