# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' LCS by DP
#'
#' @param ss a string vector.
#' @export
lcs_cc <- function(ss) {
    .Call(`_rcpptest_lcs_cc`, ss)
}

